### ISSUE TITLE
Inject LUX to the head

### ISSUE THREAD

**Issue by pi0** [hecktarzuli/speedcurve-module#1]
As mentioned in both [start guide](https://support.speedcurve.com/en/articles/1266080-get-started-with-lux-real-user-monitoring) and [notice about tag managers](https://support.speedcurve.com/en/articles/2438699-lux-snippet-and-tag-managers), we should start performance measurement as soon as possible. Before the hydration starts and nuxt executes plugins, almost all scripts are already prefetched, parsed or executed so we may have miss CPU timings (this at least noticed in docs)

> Where to insert the snippet
The lux.js script is loaded asynchronously so it won't harm the performance of your site. It's best to put the LUX snippet as early in the page as possible, i.e., at the top of the HEAD element. 

### Possible Solutions

1. One way would be using `vue-meta` and push script within module like this:

```js
  this.options.head.script.push({
    hid: 'lux',
    innerHTML: '<long script>'
  })
```

2. It can be also done at runtime via plugin (SSR) to inject but is little bit tricky. An example is [here](https://github.com/nuxt-community/gtm-module/blob/master/lib/plugin.js#L30). This is required if snippet is depending on some config (like current runtimeConfig possibility)

3. Not sticking with original snippet may be hacky and breaking in the future but since we are already doing, we may partially inject option independent lines ([here](https://github.com/hecktarzuli/speedcurve-module/blob/master/lib/plugin.js#L84)) which just initialize PerformanceObserver and then we can do rest of stuff in plugin.

**Comment by hecktarzuli** [comment]
1) I was considering this as well.  Since the default script is async if things aren't avail after the script spin-up some metrics may be dropped no matter what.  I'm working with Speedcurve right now to see if these things make a big difference or not.

Loading via GTM is the worst, loading via a plugin isn't nearly as bad.. Head of course is best if I can make it work.

3) If I do 1), I'll likely keep the original snippet and just inject it.

**Comment by pi0** [comment]
>  loading via a plugin isn't nearly as bad.. 

It is the same concept even if not worst. With either methods, another script needs to be loaded to _initialize_ snippet. CDN script is async and differed but L84 should be immediately started when page starts loading so we don'e miss CPU profiling. I think if we simply add lines 84..87 to head, problem will be gone and they don't depend on options so we can defer loading actual script by nuxt :)

**Comment by hecktarzuli** [comment]
Fixed in: https://github.com/hecktarzuli/speedcurve-module/commit/fdb90f9ec97c264d8976d38608fc1b5f3952573b

**Comment by pi0** [comment]
Awesome 👍 Just a tiny point maybe worth mentioning in the docs that it is not working with `ssr: false` (or `mode: spa') OR throwing an error in module by doing the check :)

**Comment by hecktarzuli** [comment]
Yep, thanks for the reminder.  I plan on creating an example per combo to iron out how to handle edge cases, and make sure everything works as expected.
